name: "Deploy to Go Daddy Cpanel"
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: "Deploy to Cpanel via SSH"
            uses: "appleboy/ssh-action@v1.0.3"
            with:
                host: "118.139.179.251"
                username: "b4xq17v0tbnl"
                password: "AccessOpen#2505@GDSSH"
                port: 22
                script: |
                    cd kadavil-thrikkovil
                    git pull
                    php artisan config:clear
                    php artisan route:clear
                    php artisan view:clear
                    cp ../.env.production .env
                    composer install --optimize-autoloader --no-dev
                    php artisan key:generate
                    php artisan config:cache
                    php artisan route:cache
                    php artisan view:cache 
